name: yfi-buyer
plugins:
  - vyper
  - solidity
  - tokens
  - hardhat
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat
hardhat:
  port: auto
deployments:
  ethereum:
    mainnet:
      - contract_type: YfiBuyer
        address: 0xdf5e4E54d212F7a01cf94B3986f40933fcfF589F
